FROM node:20-alpine3.19

WORKDIR /app
COPY ./package.json ./yarn.lock .yarnrc.yml ./
RUN yarn install
COPY . .
EXPOSE 80
# created dev80 to keep both dev and prod on same port for nginx
CMD ["yarn", "dev80", "--host"]
