sudo: required
services:
  - docker

before_install:
  - cd flask
  - docker build -t zachneill/gabduel -f Dockerfile .
  - cd ..


script:
  - docker-compose up db -d
  - docker-compose up -d
  - cd flask
#  - python -m pip install -r requirements.txt
  - python -m pip install pylint
  - python -m pylint app
#  - python -m coverage run -m pytest
#  - python -m coverage report --omit="*/test*,*/__init__.py,database.py,*/conftest.py"
  - cd ..
  - docker-compose down

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "gabduel"
  env: "Gabduel-env"
  bucket_name: "elasticbeanstalk-us-east-2-994472286080"
  bucket_path: "gabduel"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"