version: "3.8"
services:
  web:
    build: ./
    container_name: gd-web
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    environment:
      FLASK_ENV: development
      FLASK_APP: app.py