version: "3.9"

services:
  web:
    container_name: web
    image: zachneill/gabduel:latest
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_URL=postgresql://postgres:postgres@db:5432/gabduel
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:16-alpine3.19
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=gabduel
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}