version: "3.9"

services:
  web:
    container_name: web
    build:
      dockerfile: Dockerfile  # Dockerfile.dev for development, Dockerfile for production
      context: ./frontend
    restart: on-failure
    volumes:
      - /app/node_modules
      - ./frontend:/app
    ports:
      - "4200"
      - "4200:80"
  api:
    container_name: api
    build:
      context: api
      dockerfile: Dockerfile  # Dockerfile.dev for development, Dockerfile for production
    restart: on-failure
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/gabduel
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
  nginx:
    container_name: nginx
    build:
      context: nginx
      dockerfile: Dockerfile
    volumes:
      - ./nginx/default.conf:/etc/nginx/default.conf:ro
    ports:
      - "8081:80"
      - "443:443"
  db:
    container_name: db
    image: postgres:16-alpine3.19
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=gabduel
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}