version: "3.9"

services:
  web:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    ports:
      - "5173"
  api:
    image: zachneill/gabduel:latest
    build:
      context: api
      dockerfile: Dockerfile  # Dockerfile.dev for development, Dockerfile for production
    restart: on-failure
    volumes: ['./api:/app']  # Comment out for production
    deploy:
      replicas: 2
    ports:
      - "5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/gabduel
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    image: nginx:1.25.3-alpine3.18
    volumes:
      - ./frontend/nginx/default.conf:/etc/nginx/default.conf:ro
    ports:
      - "8080:80"
      - "443:443"
    depends_on:
      - web
  db:
    container_name: db
    image: postgres:16-alpine3.19
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=gabduel
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}