name: Docker Image CI for GHCR

on: push

jobs:
  build_and_publish:
    runs_on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push image
        run: |
          docker login --username zachneill --password ${{ secrets.GHCR_PAT }} ghcr.io
          docker build . --tag ghcr.io/zachneill/gabduel:latest
          docker push ghcr.io/zachneill/gabduel:latest